### ISSUE TITLE
Please add some usage instructions

### ISSUE THREAD

**Issue by sschuberth** [ephemient/kotlinx-serialization-contrib#1]
Can we please get some instructions how to use this in an existing project that uses `kotlinx.serialization` to (de-)serialize e.g. `enum`s in lowercase?

**Comment by ephemient** [comment]
The `test` project has always demonstrated usage, and a README and binary packages have been added in a4e0262b823e665e8549b5191a1d0e63e261b12e and c76e782904d123cc855b4b594f25a15acb0cd070.

**Comment by sschuberth** [comment]
Thank you!
